name: "Create gitleaks file regex config"
description: "make a custom gitleaks regex file to detect leaked secrets"

runs:
  using: "composite"
  steps:
    - name: Create SecretChecks.toml file
      id: create_file
      shell: bash
      run: |
        cat >SecretChecks.toml <<EOL
        title = "gitleaks config"

        [allowlist]
        description = "global allow lists"
        paths = [
            '''gitleaks.toml''',
            '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket)$''',
            '''(go.mod|go.sum)$''',
            '''node_modules''',
            '''vendor''',
        ]

        [[rules]]
        description = "Adafruit API Key"
        id = "adafruit-api-key"
        regex = '''(?i)(?:adafruit)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=|\x60){0,5}([a-z0-9_-]{32})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
        secretGroup = 1
        keywords = [
            "adafruit",
        ]

        [[rules]]
        description = "Adobe Client ID (OAuth Web)"
        id = "adobe-client-id"
        regex = '''(?i)(?:adobe)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=|\x60){0,5}([a-f0-9]{32})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
        secretGroup = 1
        keywords = [
            "adobe",
        ]
        EOL      