name: "Create gitleaks file regex config"
description: "make a custom gitleaks regex file to detect leaked secrets"

runs:
  using: "composite"
  steps:
    - name: Create SecretChecks.toml file
      id: create_file
      shell: bash
      run: |
        wget https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml
        mv gitleaks.toml SecretChecks.toml      